name: RCMDcheck

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  RCMDcheck:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        config: 
        - {os: windows-latest, r: '4.0',   vdiffr: true,  xref: true}
        - {os: macOS-latest,   r: '4.0',   vdiffr: true,  xref: true}
        - {os: ubuntu-16.04,   r: '4.0', vdiffr: false, xref: true}
          

    steps:
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@ffe45a39586f073cc2e9af79c4ba563b657dc6e3
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning")
        shell: Rscript {0}
